### ISSUE TITLE
HL2VRU_0.0.4.7z flagged for containing a virus

### ISSUE THREAD

**Issue by hobyvh** [vittorioromeo/HL2VRU#1]
When I attempted to download HL2VRU_0.0.4.7z in Chrome (current) in Windows 11, it failed because of a virus warning.

Windows antivirus reports finding Trojan:Script/Wacatac.B!ml

**Comment by vittorioromeo** [comment]
I don't really know what to do about this, searching online shows that other people have had issues with their C++ programs being registered as false positives.

HL2VRU is safe, it's an issue with Windows Defender mistakenly detecting the binaries as viruses. You should be able to set an exception in Windows Defender for HL2VRU explicitly, allowing you to install the mod.
