### ISSUE TITLE
broken by recent hl2 vr update?

### ISSUE THREAD

**Issue by vb87** [vittorioromeo/HL2VRU#10]
did a recent hl2 vr update break this mod?

there are a lot of files modified in november, but only two dll files:
game_shader_generic_hlvr.dll
game_shader_generic_source.dll

I am not able to select weapons on either hand and the melee attack does not seem to work either

**Comment by vittorioromeo** [comment]
This version should work, please re-open the issue if you still have trouble:
https://github.com/vittorioromeo/HL2VRU/releases/tag/v0.0.6
