### ISSUE TITLE
Shotgun Alternate fire no longer works

### ISSUE THREAD

**Issue by qwertylesh** [vittorioromeo/HL2VRU#4]
In HL2VR, you can press the Alt-fire button and the shotgun will release more than one shell, as opposed to one shell with normal fire. this behavior is also present in the Flat HL2. 
When HL2VRU is installed, the alt-fire capability for the shotgun no longer works, the behavior observed is that the gun doesn't fire at all.

**Comment by vittorioromeo** [comment]
Fixed for next release.
