### ISSUE TITLE
two handed weapon handling lacks the wrist position axis rotation

### ISSUE THREAD

**Issue by qwertylesh** [vittorioromeo/HL2VRU#8]
player ThirdChoice from discord reports, once the mod is installed, only the two handed weapons while being held two handed, behave with a single angle calculation ( hand 1 and hand 2 angle) but that the behavior of non-modded HL2VR mod can do both hand1+2 angle and also wrist/rotation angles too.

They've shared a Gif ( https://i.imgur.com/yHOJyVD.gifv ) demonstrating how when the weapon is held two handed it snaps upright into place and disallows the base vrmod capability.

**Comment by Grammernatzi** [comment]
Is this with virtual stock on? Have you tried turning it off?

**Comment by Grammernatzi** [comment]
Yeah, I was able to confirm it too, though it doesn't seem to affect the pistols like it does there. But I'm also not using the latest version, I'm using the one before they added weapon weight.

**Comment by Munkilicious** [comment]
Here's a video of it... probably mute the audio
https://youtu.be/pqPf_5GiYPo

**Comment by Tetraden** [comment]
I can confirm the behaviour with 0.0.6
Independent of the virtual gun stock settings.

**Comment by vittorioromeo** [comment]
Should be fixed in latest version https://github.com/vittorioromeo/HL2VRU/releases/tag/v0.0.7
