### ISSUE TITLE
Option to disable dual wield

### ISSUE THREAD

**Issue by jnTracks** [vittorioromeo/HL2VRU#9]
(forgive me if this isn't the right way to ask about this, but I'm not very familiar with github and don't see another way to ask a question or suggest)

Is there some way to disable the dual-wield aspect of this mod so the rest of it still works but the left hand doesn't worry about holding weapons and the controls on left hand function normally? 
I love the virtual stock, which I feel was sorely missing from HL2VR and the other aspects are fun, but I'm wishing had back the original left hand controls instead of dual wield.
Is there something I could edit, or is there a menu toggle that I missed?
Thanks!

**Comment by vittorioromeo** [comment]
As mentioned above, you already achieve this by tweaking your SteamVR bindings.
